# Generated by Django 3.2.12 on 2022-10-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_hooks', '0002_swappable_hook_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='app',
            field=models.CharField(choices=[('zapier', 'Zapier'), ('prvolt', 'PR-Volt')], default='prvolt', max_length=15),
        ),
        migrations.AlterField(
            model_name='hook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
